// <auto-generated />
using System;
using Kris.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kris.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250531162528_UpdateRegistrationEntityRelationships")]
    partial class UpdateRegistrationEntityRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfStudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("YearOfStudyId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1 Red",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "1 Blue",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "1 Yellow",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "2 Red",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "2 Blue",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "2 Yellow",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "3 Red",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "3 Blue",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "3 Yellow",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "4 Red",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "4 Blue",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "4 Yellow",
                            YearOfStudyId = 4
                        });
                });

            modelBuilder.Entity("Kris.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Physics Olympiad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chemistry Challenge"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biology Competition"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mathematics Tournament"
                        });
                });

            modelBuilder.Entity("Kris.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssociationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfStudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("YearOfStudyId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Kris.Models.YearOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YearsOfStudy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Form 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Form 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Form 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Form 4"
                        });
                });

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.HasOne("Kris.Models.YearOfStudy", "YearOfStudy")
                        .WithMany("Classes")
                        .HasForeignKey("YearOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YearOfStudy");
                });

            modelBuilder.Entity("Kris.Models.Registration", b =>
                {
                    b.HasOne("Kris.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kris.Models.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kris.Models.YearOfStudy", "YearOfStudy")
                        .WithMany()
                        .HasForeignKey("YearOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Competition");

                    b.Navigation("YearOfStudy");
                });

            modelBuilder.Entity("Kris.Models.YearOfStudy", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
