// <auto-generated />
using System;
using Kris.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kris.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250531170604_AddStudentsAndUpdateRegistration")]
    partial class AddStudentsAndUpdateRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfStudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("YearOfStudyId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1 Red",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "1 Blue",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "1 Yellow",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "2 Red",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "2 Blue",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "2 Yellow",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "3 Red",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "3 Blue",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "3 Yellow",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "4 Red",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "4 Blue",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "4 Yellow",
                            YearOfStudyId = 4
                        });
                });

            modelBuilder.Entity("Kris.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Physics Olympiad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chemistry Challenge"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biology Competition"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mathematics Tournament"
                        });
                });

            modelBuilder.Entity("Kris.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssociationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Kris.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfStudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("YearOfStudyId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Name = "Adam Smith",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            Name = "Beth Johnson",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            Name = "Charlie Brown",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            Name = "David Lee",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            Name = "Emma Wilson",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            Name = "Frank Chen",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 4,
                            Name = "Grace Kim",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 4,
                            Name = "Henry Tan",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 4,
                            Name = "Ivy Zhang",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 5,
                            Name = "Jack Wong",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 5,
                            Name = "Katie Davis",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 5,
                            Name = "Liam Miller",
                            YearOfStudyId = 2
                        });
                });

            modelBuilder.Entity("Kris.Models.YearOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YearsOfStudy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Form 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Form 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Form 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Form 4"
                        });
                });

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.HasOne("Kris.Models.YearOfStudy", "YearOfStudy")
                        .WithMany("Classes")
                        .HasForeignKey("YearOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YearOfStudy");
                });

            modelBuilder.Entity("Kris.Models.Registration", b =>
                {
                    b.HasOne("Kris.Models.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kris.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kris.Models.Student", b =>
                {
                    b.HasOne("Kris.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kris.Models.YearOfStudy", "YearOfStudy")
                        .WithMany("Students")
                        .HasForeignKey("YearOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("YearOfStudy");
                });

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Kris.Models.YearOfStudy", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
