// <auto-generated />
using System;
using Kris.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kris.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603154342_PreventDuplicateRegistrations")]
    partial class PreventDuplicateRegistrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Kris.Models.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Associations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Environment Club"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Club"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Math Club"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Robotics Club"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Innovation Club"
                        });
                });

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfStudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("YearOfStudyId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1 Red",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "1 Blue",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "1 Yellow",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "2 Red",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "2 Blue",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "2 Yellow",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "3 Red",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "3 Blue",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "3 Yellow",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "4 Red",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "4 Blue",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "4 Yellow",
                            YearOfStudyId = 4
                        });
                });

            modelBuilder.Entity("Kris.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Physics Olympiad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chemistry Challenge"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biology Competition"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mathematics Tournament"
                        });
                });

            modelBuilder.Entity("Kris.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssociationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Kris.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfStudyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("YearOfStudyId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Name = "Adam Smith",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            Name = "Beth Johnson",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            Name = "Charlie Brown",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            Name = "Diana Ross",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            Name = "Edward Lee",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            Name = "Fiona Wilson",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 2,
                            Name = "George Chen",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 2,
                            Name = "Hannah Liu",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 3,
                            Name = "Ian Foster",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 3,
                            Name = "Julia Zhang",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 3,
                            Name = "Kevin Patel",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 3,
                            Name = "Lucy Wang",
                            YearOfStudyId = 1
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 4,
                            Name = "Michael Kim",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 4,
                            Name = "Nancy Chen",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 4,
                            Name = "Oliver Tan",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 4,
                            Name = "Patricia Lee",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 5,
                            Name = "Quincy Adams",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 5,
                            Name = "Rachel Green",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 5,
                            Name = "Samuel Liu",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 5,
                            Name = "Tracy Wong",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 6,
                            Name = "Uma Patel",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 6,
                            Name = "Victor Zhang",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 6,
                            Name = "Wendy Davis",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 6,
                            Name = "Xavier Chen",
                            YearOfStudyId = 2
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 7,
                            Name = "Yolanda Kim",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 7,
                            Name = "Zack Miller",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 7,
                            Name = "Alice Wang",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 7,
                            Name = "Bob Taylor",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 8,
                            Name = "Carol Lee",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 8,
                            Name = "David Chen",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 8,
                            Name = "Emily Liu",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 8,
                            Name = "Frank Zhang",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 9,
                            Name = "Grace Park",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 9,
                            Name = "Henry Wu",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 9,
                            Name = "Iris Chen",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 9,
                            Name = "Jack Wong",
                            YearOfStudyId = 3
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 10,
                            Name = "Kelly Tan",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 10,
                            Name = "Leo Martinez",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 10,
                            Name = "Maria Garcia",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 10,
                            Name = "Nathan Lee",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 11,
                            Name = "Olivia Wilson",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 11,
                            Name = "Peter Zhang",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 11,
                            Name = "Quinn Chen",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 11,
                            Name = "Rosa Kim",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 12,
                            Name = "Steve Wang",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 12,
                            Name = "Tina Liu",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 47,
                            ClassId = 12,
                            Name = "Ulysses Park",
                            YearOfStudyId = 4
                        },
                        new
                        {
                            Id = 48,
                            ClassId = 12,
                            Name = "Victoria Chen",
                            YearOfStudyId = 4
                        });
                });

            modelBuilder.Entity("Kris.Models.YearOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YearsOfStudy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Form 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Form 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Form 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Form 4"
                        });
                });

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.HasOne("Kris.Models.YearOfStudy", "YearOfStudy")
                        .WithMany("Classes")
                        .HasForeignKey("YearOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YearOfStudy");
                });

            modelBuilder.Entity("Kris.Models.Registration", b =>
                {
                    b.HasOne("Kris.Models.Association", "Association")
                        .WithMany("Registrations")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kris.Models.Competition", "Competition")
                        .WithMany("Registrations")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kris.Models.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Association");

                    b.Navigation("Competition");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kris.Models.Student", b =>
                {
                    b.HasOne("Kris.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kris.Models.YearOfStudy", "YearOfStudy")
                        .WithMany("Students")
                        .HasForeignKey("YearOfStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("YearOfStudy");
                });

            modelBuilder.Entity("Kris.Models.Association", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Kris.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Kris.Models.Competition", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Kris.Models.Student", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Kris.Models.YearOfStudy", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
